### ISSUE TITLE
Config File Not Present

### ISSUE THREAD

**Issue by Johnnyreyman** [traumweh/duckypad_daemon#1]
I have installed the duckypad_autoswitcher from the AUR and the daemon reports:
`thread 'main' panicked at 'Config file isn't present', src/lib.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

System Info:
`Linux Synolvia-Enterprise 6.0.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 29 Oct 2022 14:08:39 +0000 x86_64 GNU/Linux`

**Comment by traumweh** [comment]
The Daemon requires the autoswitcher config to be present and currently doesn't create it on its own, but I could easily change that. I'm also thinking about adding a cli parameter to manually set a config-path.

For troubleshooting reasons:
1.) Did you run the autoswitcher gui beforehand and made any settings?
2.) Does the data directory (`~/.local/share/duckypad_autoswitcher/` or `$XDG_DATA_DIR/duckypad_autoswitcher/`) exist?
3.) Does a file called `config.txt` exist inside that directory?

**Comment by traumweh** [comment]
I pushed a fix that automatically creates a default config.txt if it doesn't exists yet. This should get created in the directory that the autoswitcher gui would look at. If this didn't fix your problem, simply reopen the issue and I'll look into it. c:

Optionally one can use `-c <file-path>` or `--config <file-path>` to specify a custom config.
