### ISSUE TITLE
Running on a mac, "Failed to connect to duckyPad"

### ISSUE THREAD

**Issue by remy** [traumweh/duckypad_daemon#2]
I managed to install the daemon (I needed the latest `rustc` otherwise rust gives an unhelpful error about not finding the `clap` package). But running (with the ducky connected) fail with the following:

```
$ RUST_BACKTRACE=1 duckypad_daemon -c ~/Library/Application\ Support/duckypad_autoswitcher/config.txt

duckypad daemon started!
thread 'main' panicked at 'Failed to connect to duckyPad. See --help if you want to enable auto-retrying.: HidApiError { message: "hid_error is not implemented yet" }', src/main.rs:54:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::expect
   4: duckypad_daemon::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Any ideas? I'm not familiar with Rust, but I might be able to debug.

Though now skimming the code, I'm going to guess if it relies on X11 (isn't that the linux gui manager?) then it's not going to fly at all on the mac…?

**Comment by traumweh** [comment]
The error seems to be a hid error.
1) Did you use dekuNukems python autoswitcher before?
2) Does the duckypad_daemon have all permissions to read from and write to the hid device?

But currently the daemon indeed relies on X11 to figure out what window is currently focused. Meaning it currently supports neither Mac nor Windows nor Linux Wayland.
I'm not running a Mac, but I'd be happy to implement something that works on Mac as well, tho that wouldn't be that high on my priority list right now. But if you or someone wants to work on it, I'd be happy to help where I can.

**Comment by remy** [comment]
Cheers - on (1) - yes, all running fine (the config I was passing came from the switcher too). 

On (2) - apparently not - I re-ran as root and it did get past the error and then immediately crashed into the X11 call.

Appreciate the reply, and appreciate that mac support is low/null - if I find myself with dire urge to get it working too, I could have a go (or at least port it to a language I can read myself, if only for my own machine). 

Thanks again.

**Comment by remy** [comment]
(oh, feel free to close this - I'd say the main issue I raised is solved)

**Comment by traumweh** [comment]
Hey there! I'm currently working on adding support for Windows, macOS and Linux Wayland and created the `multiplatform` branch for it. But I am unable to test on macOS and only to some extent on Windows via a virtual machine. So if someone wants to help, then please have a look at the respective issue: #3 (macOS), #4 (Windows) and #5 (Wayland).
